#!/usr/bin/env python3
"""
Varahi content generator.

Source of truth: src/content/**/*.md  (frontmatter + markdown body)
Output:          src/data/content.generated.ts  (typed, zero runtime deps)

Run after editing any .md:   python3 scripts/gen_content.py

Why generate instead of parsing at runtime: keeps the browser bundle free of
gray-matter/marked and their Buffer polyfills, and gives us type safety.
"""
import json, os, re, sys
import yaml, markdown

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT = os.path.join(ROOT, "src", "content")
OUT = os.path.join(ROOT, "src", "data", "content.generated.ts")

# Pillar assignment is CURATED, not inferred. 15 pieces do not need a heuristic,
# and tag-matching mis-filed the RAG case study under SAP. Edit this map when
# adding content; an unmapped slug fails the build loudly rather than guessing.
PILLARS = {
    # Case studies — the founder's delivery record (real, founder-attributed)
    "zoox-autonomous-fleet-service":           "ai",
    "yaskawa-robotics-service-transformation": "sap",
    "argano-cx-s4-integration":                "cx",
    "carlisle-lbfoster-sales-service-cpq":     "sap",
    "weyerhaeuser-service-transformation":     "sap",
    "heavy-machinery-connected-service":       "ai",
    "carestream-capital-equipment-service":    "cx",
    # Insights
    "s4-clean-core-ai-readiness":       "sap",
    "sap-service-ops-data-contracts":   "sap",
    "industrial-field-service-cx-gap":  "cx",
    "s4hana-rise-migration-decisions":  "sap",
    "sap-needs-an-ai-plan":             "ai",
    "core-ai-evaluation-playbook":      "ai",
    "sap-ai-use-cases-that-scale":      "ai",
    "agent-governance-for-enterprises": "ai",
    "sap-ai-copilot-role-design":       "ai",
    "agentic-ai-handoff-problem":       "ai",
}

def pillar_for(slug):
    if slug not in PILLARS:
        sys.exit(f"ERROR: no pillar mapped for '{slug}'. Add it to PILLARS in scripts/gen_content.py")
    return PILLARS[slug]

def split_fm(raw):
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n(.*)$", raw, re.S)
    if not m:
        raise ValueError("missing frontmatter")
    return yaml.safe_load(m.group(1)) or {}, m.group(2).strip()

def read_dir(kind):
    d = os.path.join(CONTENT, kind)
    if not os.path.isdir(d):
        return []
    items = []
    for name in sorted(os.listdir(d)):
        if not name.endswith(".md"):
            continue
        with open(os.path.join(d, name), encoding="utf-8") as f:
            fm, body = split_fm(f.read())
        if fm.get("draft"):
            print(f"  skip (draft): {name}")
            continue
        slug = re.sub(r"^\d{4}-\d{2}-\d{2}-", "", name[:-3])
        tags = fm.get("tags", []) or []
        html = markdown.markdown(body, extensions=["extra", "sane_lists"])
        item = {
            "slug": slug,
            "kind": kind,
            "title": fm["title"],
            "description": fm.get("description", ""),
            "pubDate": str(fm.get("pubDate", "")),
            "tags": tags,
            "pillar": pillar_for(slug),
            "readingMinutes": max(1, round(len(body.split()) / 220)),
            "html": html,
        }
        if kind == "work":
            item.update({
                "client": fm.get("client", ""),
                "role": fm.get("role", ""),
                "industry": fm.get("industry", ""),
                "year": fm.get("year"),
                "metrics": fm.get("metrics", []) or [],
            })
        else:
            item["author"] = fm.get("author", "Varahi")
        items.append(item)
    items.sort(key=lambda i: i["pubDate"], reverse=True)
    return items

def main():
    insights = read_dir("insights")
    work = read_dir("work")
    ts = f"""// AUTO-GENERATED by scripts/gen_content.py - do not edit by hand.
// Source of truth: the markdown under src/content
// Regenerate: python3 scripts/gen_content.py

export type Pillar = 'sap' | 'ai' | 'cx';

export interface Metric {{ label: string; value: string; }}

export interface Insight {{
  slug: string; kind: 'insights'; title: string; description: string;
  pubDate: string; tags: string[]; pillar: Pillar; readingMinutes: number;
  author: string; html: string;
}}

export interface CaseStudy {{
  slug: string; kind: 'work'; title: string; description: string;
  pubDate: string; tags: string[]; pillar: Pillar; readingMinutes: number;
  client: string; role: string; industry: string; year: number; metrics: Metric[]; html: string;
}}

export const insights: Insight[] = {json.dumps(insights, indent=2, ensure_ascii=False)};

export const caseStudies: CaseStudy[] = {json.dumps(work, indent=2, ensure_ascii=False)};

export const allContent = [...caseStudies, ...insights];

export const byPillar = (pillar: Pillar) => allContent.filter((c) => c.pillar === pillar);
"""
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(ts)
    print(f"\n  {len(insights)} insights, {len(work)} case studies -> src/data/content.generated.ts")
    for c in work:
        print(f"    work/{c['slug']}  [{c['pillar']}]  {len(c['metrics'])} metrics")
    for i in insights:
        print(f"    insights/{i['slug']}  [{i['pillar']}]")

    write_sitemap(insights, work)

BASE = "https://thevarahi.com"
# Canonical, indexable pages only — never list the /agentic, /what-we-do,
# /services/* etc. redirects.
STATIC_ROUTES = [
    ("/", "1.0", "weekly"),
    ("/practice", "0.9", "monthly"),
    ("/sap", "0.9", "monthly"),
    ("/ai", "0.9", "monthly"),
    ("/cx", "0.9", "monthly"),
    ("/approach", "0.8", "monthly"),
    ("/our-thinking", "0.8", "weekly"),
    ("/about", "0.7", "monthly"),
    ("/engage", "0.6", "monthly"),
]

def write_sitemap(insights, work):
    out = os.path.join(ROOT, "public", "sitemap.xml")
    today = max([i["pubDate"] for i in insights + work] + ["2026-07-13"])
    rows = []
    for path, prio, freq in STATIC_ROUTES:
        rows.append(
            f"  <url>\n    <loc>{BASE}{path}</loc>\n    <lastmod>{today}</lastmod>\n"
            f"    <changefreq>{freq}</changefreq>\n    <priority>{prio}</priority>\n  </url>"
        )
    for c in work + insights:
        loc = f"{BASE}/our-thinking/{c['kind']}/{c['slug']}"
        rows.append(
            f"  <url>\n    <loc>{loc}</loc>\n    <lastmod>{c['pubDate']}</lastmod>\n"
            f"    <changefreq>yearly</changefreq>\n    <priority>0.7</priority>\n  </url>"
        )
    xml = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "\n".join(rows)
        + "\n</urlset>\n"
    )
    with open(out, "w", encoding="utf-8") as f:
        f.write(xml)
    print(f"  sitemap -> public/sitemap.xml ({len(STATIC_ROUTES) + len(work) + len(insights)} urls)")

if __name__ == "__main__":
    main()
